---

- name: cisco_clear_arp
  hosts: "{{ host_name }}"
  gather_facts: false


  tasks:

   - name: run clear arp command
     cisco.ios.ios_command:
      commands: 'clear arp-cache {{ ip_address }}'
